export const ErrorMessages = {
  EXPECT_POSITIVE_INVOICE_AMOUNT : "EXPECT_POSITIVE_INVOICE_AMOUNT",
  EXPECT_FRACTION_INSURANCE_RATE: "EXPECT_FRACTION_INSURANCE_RATE",
  EXPECT_POSITIVE_IMPORT_DELIVERY: "EXPECT_POSITIVE_IMPORT_DELIVERY",
};