export const ErrorMessages = {
  AMOUNT_TO_BE_PAID: "AMOUNT_TO_BE_PAID",
  PAY_AGENT_PLAN: "PAY_AGENT_PLAN",
  CURRENCY_EXPECTED: "CURRENCY_EXPECTED",
}

export const BASE_CURRENCY = "RUR";

export const BONDED_STORAGE_AND_DECLARATION = 24000;
export const BONDED_STORAGE_CURRENCY = BASE_CURRENCY;
export const COMPENSATION_AMOUNT = 3500;
export const COMPENSATION_CURRENCY  = BASE_CURRENCY;